require:
  - rubocop-rspec

AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 2.7
  Include:
    - 'app/**/*.rb'
  Exclude:
    - 'app/views/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/bundle/**/*'
    - 'node_modules/**/*'


Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
